name: Daily Scrape

on:
  schedule:
    - cron: "30 3 * * *"   # 9:00 AM IST daily
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/scrape.yml"
      - "scraper.py"
      - "requirements.txt"
      - "data/**"
      - "websites_list.*"      # lets you run it manually from the Actions tab

permissions:
  contents: write           # allow pushing updated JSON files

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: tfbdmap-scrape
      cancel-in-progress: true

    env:
      PYTHONUNBUFFERED: "1"         # cleaner logs
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Instal
